--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Taylor-pm-pl/Bard-AI
build-by-default: true
branches:
- pm4
- pm5
projects:
  Bard-AI:
    icon: "asset/img/logo.png"
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
      - src: taylordevs/Meet-Bard/Meet-Bard
        version: ^1.0.1
...
